version: '3.8'

services:
  postman:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - redis
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - webeye-postman-dev-redis-data:/data

volumes:
  webeye-postman-dev-redis-data: