version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: api_db,bot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

  redis:
    image: redis
    restart: always

  api:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  checker:
    build:
      context: checker
      dockerfile: Dockerfile
    restart: always
    env_file:
      - checker/.env
    depends_on:
      - api
    links:
      - api

  postman:
    build:
      context: postman
      dockerfile: Dockerfile
    restart: always
    env_file:
      - postman/.env
    links:
      - redis

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8490:3000"
    env_file:
      - frontend/.env
    depends_on:
      - api
    links:
      - api

  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    restart: always
    env_file:
      - bot/.env
    depends_on:
      - api
    links:
      - api
      - redis
      - postgres

volumes:
  pgdata:
