version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

